W14D1/W14D1| - React Router/6 - componentDidUpdate/bleater/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # get "/bleats", to: "bleats#index"

  # get "/bleats/:id", to: "bleats#show"

  # post "/bleats", to: "bleats#create"

  # put "/bleats/:id", to: "bleats#update"

  # delete "/bleats/:id", to: "bleats#destroy"
  # resources :bleats

  # resources :users, only: [:new, :create]

  resource :session, only: [:new, :create, :destroy]

  # get "/get_cookie", to: "cookie_demos#get_cookie"
  # get "/set_cookie", to: "cookie_demos#set_cookie"
  root to: "static_pages#root"

  namespace :api, defaults: {format: :json} do
    resources :bleats, only: [:index, :show, :create]
  end
end

W14D1/W14D1| - React Router/6 - componentDidUpdate/bleater/app/models/bleat.rb
# == Schema Information
#
# Table name: bleats
#
#  id         :bigint(8)        not null, primary key
#  body       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  author_id  :integer
#

class Bleat < ApplicationRecord

  # validate :ensure_bleats_arent_long
  validates :body, presence: true
  validates :body, length: {maximum: 150}

  belongs_to :author,
    class_name: "User",
    primary_key: :id,
    foreign_key: :author_id
    # optional: true

  has_one :location,
    through: :author,
    source: :location


  # def ensure_bleats_arent_long
  #   self
  #   if self.body && self.body.length > 150
  #     self.errors[:body] << "is too long (max is 150 chars)"
  #   end
  # end
end

W14D1/W14D1| - React Router/6 - componentDidUpdate/bleater/app/controllers/api/bleats_controller.rb
class Api::BleatsController < ApplicationController

  def index
    # sleep(3)
    @bleats = Bleat.includes(author: :authored_bleats).all
    # render json: bleats
    render :index
  end

  def show
    bleat = Bleat.find(params[:id])
    @bleats = [bleat]
    render :index
  end

  def create
    bleat = Bleat.new(bleat_params)

    if bleat.save
      render json: bleat
    else
      render json: bleat.errors.full_messages, status: 422
    end
  end

  private
  def bleat_params
    params.require("bleat").permit(:body, :author_id)
  end

end

W14D1/W14D1| - React Router/6 - componentDidUpdate/bleater/app/controllers/bleats_controller.rb
class BleatsController < ApplicationController

  before_action :ensure_user_logged_in, only: [:create, :new, :edit, :update, :destroy]

  def index
    # render plain: "Hello, World!"
    # render json: '{"tommy": "hello"}'
    # @bleats = Bleat.includes(:author).all
    render :index
  end

  def show
    @bleat = Bleat.find(params[:id])
    render :show
  end

  def new
    @bleat = Bleat.new
    render :new
  end

  # Potential CSRF attack on another website:
  <<-HTML
    <form action="http://bleater.com/bleats" method="POST">
      <input type="hidden" name="bleat[body]" value="All my secrets!!">
      <button>Win $1,000,000</button>
    </form>
  HTML

  def create
    # @bleat = Bleat.new(bleat_params)
    # @bleat.author_id = current_user.id
    @bleat = current_user.authored_bleats.new(bleat_params)

    if @bleat.save
      # render json: bleat
      flash[:success] = "Successfully created your bleat!"
      redirect_to bleat_url(@bleat.id)
    else
      flash.now[:error] = "Couldn't create the bleat. See below for errors."
      render :new, status: 422
    end
  end

  def edit
    @bleat = current_user.authored_bleats.find(params[:id])
    render :edit
  end

  def update
    @bleat = current_user.authored_bleats.find(params[:id])

    if @bleat.update(bleat_params)
      # render json: bleat
      redirect_to bleat_url(@bleat.id)
    else
      # render json: bleat.errors.full_messages, status: 422
      render :edit, status: 422
    end
  end

  def destroy
    bleat = current_user.authored_bleats.find(params[:id])
    bleat.destroy
    # render json: "Successfully destroyed the Bleat!"
    redirect_to bleats_url
  end

  private
  def bleat_params
    params.require(:bleat).permit(:body)
  end

end

W14D1/W14D1| - React Router/6 - componentDidUpdate/bleater/app/views/bleats/_form.html.erb
<% if bleat.persisted? %>
  <% action = bleat_url(bleat.id) %>
  <%# method_override = "PUT" %>
  <% method_override = '<input type="hidden" name="_method" value="PUT">'.html_safe %>
  <% button_text = "Update the bleat!" %>
<% else %>
  <% action = bleats_url %>
  <%# method_override = "POST" %>
  <% method_override = "" %>
  <% button_text = "Create the bleat!" %>
<% end %>


<form id="bleat-form" action="<%= action %>" method="POST">

  <%= method_override %>

  <%= auth_token %>
  
  <ul>
  <% bleat.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
  <% end %>
  </ul>

  <label>
    Body
    <input id="bleat-body" type="text" name="bleat[body]" value="<%= bleat.body %>" />
  </label>

  <button><%= button_text %></button>

</form>

W14D1/W14D1| - React Router/6 - componentDidUpdate/bleater/app/views/bleats/edit.html.erb
<h1>Edit the bleat!</h1>

<%= render "form", bleat: @bleat %>

W14D1/W14D1| - React Router/6 - componentDidUpdate/bleater/app/views/bleats/index.html.erb
<h1>Bleats Index!</h1>

<main id="root"></main>

W14D1/W14D1| - React Router/6 - componentDidUpdate/bleater/app/views/bleats/new.html.erb
<h1>Make a new Bleat!</h1>

<%= render partial: "form", locals: {bleat: @bleat} %>

W14D1/W14D1| - React Router/6 - componentDidUpdate/bleater/app/views/bleats/show.html.erb
<h1><%= @bleat.author.email %></h1>

<p><%= @bleat.body %></p>

<a href="<%= bleats_url %>">Back to index</a> | 
<% if @bleat.author == current_user %>
  <a href="<%= edit_bleat_url %>">Edit</a> |
  <form action="<%= bleat_url(@bleat.id) %>" method="POST">
    <input type="hidden" name="_method" value="DELETE" />
    <input type="submit" value="Destroy the bleat!">
  </form>
<% end %>